# Generated by Django 4.2.3 on 2023-07-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_timestamp_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
