# Generated by Django 4.2.3 on 2023-07-28 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('normal_user', 'Normal_User')], db_index=True, default='normal_user', max_length=36)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
