# Generated by Django 4.2.3 on 2023-07-28 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=224)),
                ('description', models.TextField(max_length=224)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foot')),
            ],
        ),
    ]
