# Generated by Django 4.2.3 on 2023-07-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersocial',
            table='user_socials',
        ),
    ]
